config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :parking_fees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parking_statuses
  resources :permissions
  resources :supervisors
  resources :role_of_supervisors
  resources :parking_slots
  resources :cars
  resources :customers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'parking_statuses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
  belongs_to :role_of_supervisor
  has_many :permission
end

app/controllers/supervisors_controller.rb
class SupervisorsController < ApplicationController
  before_action :set_supervisor, only: %i[ show edit update destroy ]

  # GET /supervisors or /supervisors.json
  def index
    @supervisors = Supervisor.all
  end

  # GET /supervisors/1 or /supervisors/1.json
  def show
  end

  # GET /supervisors/new
  def new
    @supervisor = Supervisor.new
  end

  # GET /supervisors/1/edit
  def edit
  end

  # POST /supervisors or /supervisors.json
  def create
    @supervisor = Supervisor.new(supervisor_params)

    respond_to do |format|
      if @supervisor.save
        format.html { redirect_to supervisor_url(@supervisor), notice: "Supervisor was successfully created." }
        format.json { render :show, status: :created, location: @supervisor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supervisors/1 or /supervisors/1.json
  def update
    respond_to do |format|
      if @supervisor.update(supervisor_params)
        format.html { redirect_to supervisor_url(@supervisor), notice: "Supervisor was successfully updated." }
        format.json { render :show, status: :ok, location: @supervisor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supervisors/1 or /supervisors/1.json
  def destroy
    @supervisor.destroy

    respond_to do |format|
      format.html { redirect_to supervisors_url, notice: "Supervisor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supervisor
      @supervisor = Supervisor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supervisor_params
      params.require(:supervisor).permit(:role_of_supervisor_id, :supervisor_name, :supervisor_DoB, :supervisor_address, :supervisor_phone)
    end
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/views/supervisors/_form.html.erb
<%= form_with(model: supervisor) do |form| %>
<% if supervisor.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(supervisor.errors.count, "error") %> prohibited this supervisor from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% supervisor.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :role_of_supervisor_id, class: label_class %>
        <%= form.select :role_of_supervisor_id, options_from_collection_for_select(
          RoleOfSupervisor.all, 'id', 'role_of_supervisor_category', selected = supervisor.role_of_supervisor_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :supervisor_name, class: label_class %>
          <%= form.text_field :supervisor_name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :supervisor_DoB, class: label_class %>
          <%= form.date_field :supervisor_DoB, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :supervisor_address, class: label_class %>
          <%= form.text_field :supervisor_address, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :supervisor_phone, class: label_class %>
          <%= form.text_field :supervisor_phone, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if supervisor.persisted? %>
<%= link_to "Cancel", supervisor, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", supervisors_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/supervisors/_supervisor.html.erb
<div id="<%= dom_id supervisor %>">
  <p>
    <strong>Role of supervisor:</strong>
    <%= supervisor.role_of_supervisor_id %>
  </p>

  <p>
    <strong>Supervisor name:</strong>
    <%= supervisor.supervisor_name %>
  </p>

  <p>
    <strong>Supervisor dob:</strong>
    <%= supervisor.supervisor_DoB %>
  </p>

  <p>
    <strong>Supervisor address:</strong>
    <%= supervisor.supervisor_address %>
  </p>

  <p>
    <strong>Supervisor phone:</strong>
    <%= supervisor.supervisor_phone %>
  </p>

</div>

app/views/supervisors/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit supervisor</h1>
    <% if @supervisor.persisted? %>
    <%= button_to 'Destroy', @supervisor, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', supervisor: @supervisor %>
</div>

app/views/supervisors/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Supervisors</h1>

    <%= link_to new_supervisor_path, class: button_class(theme: "primary") do %>
    Add New Supervisor
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Role of supervisor</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Supervisor name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Supervisor dob</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Supervisor address</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Supervisor phone</th>
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @supervisors.each do |supervisor| %>
      <%= content_tag :tr, id: dom_id(supervisor), class: dom_class(supervisor) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supervisor.role_of_supervisor.role_of_supervisor_category %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supervisor.supervisor_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supervisor.supervisor_DoB %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supervisor.supervisor_address %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= supervisor.supervisor_phone %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', supervisor %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/supervisors/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New supervisor</h1>

  <%= render 'form', supervisor: @supervisor %>
</div>

app/views/supervisors/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Supervisor</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to supervisors_path, class: button_class(theme: "transparent") do %>
      All Supervisors
      <% end %>
      <%= link_to edit_supervisor_path(@supervisor), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Role of supervisor:</p>
        <p><%= @supervisor.role_of_supervisor.role_of_supervisor_category %></p>
      </li>
      <li>
        <p class="font-semibold">Supervisor name:</p>
        <p><%= @supervisor.supervisor_name %></p>
      </li>
      <li>
        <p class="font-semibold">Supervisor dob:</p>
        <p><%= @supervisor.supervisor_DoB %></p>
      </li>
      <li>
        <p class="font-semibold">Supervisor address:</p>
        <p><%= @supervisor.supervisor_address %></p>
      </li>
      <li>
        <p class="font-semibold">Supervisor phone:</p>
        <p><%= @supervisor.supervisor_phone %></p>
      </li>
  </ul>
</div>