config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :parking_fees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parking_statuses
  resources :permissions
  resources :supervisors
  resources :role_of_supervisors
  resources :parking_slots
  resources :cars
  resources :customers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'parking_statuses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/parking_fee.rb
class ParkingFee < ApplicationRecord
  has_many :parking_status
end

app/controllers/parking_fees_controller.rb
class ParkingFeesController < ApplicationController
  before_action :set_parking_fee, only: %i[ show edit update destroy ]

  # GET /parking_fees or /parking_fees.json
  def index
    @parking_fees = ParkingFee.all
  end

  # GET /parking_fees/1 or /parking_fees/1.json
  def show
  end

  # GET /parking_fees/new
  def new
    @parking_fee = ParkingFee.new
  end

  # GET /parking_fees/1/edit
  def edit
  end

  # POST /parking_fees or /parking_fees.json
  def create
    @parking_fee = ParkingFee.new(parking_fee_params)

    respond_to do |format|
      if @parking_fee.save
        format.html { redirect_to parking_fee_url(@parking_fee), notice: "Parking fee was successfully created." }
        format.json { render :show, status: :created, location: @parking_fee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parking_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_fees/1 or /parking_fees/1.json
  def update
    respond_to do |format|
      if @parking_fee.update(parking_fee_params)
        format.html { redirect_to parking_fee_url(@parking_fee), notice: "Parking fee was successfully updated." }
        format.json { render :show, status: :ok, location: @parking_fee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking_fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_fees/1 or /parking_fees/1.json
  def destroy
    @parking_fee.destroy

    respond_to do |format|
      format.html { redirect_to parking_fees_url, notice: "Parking fee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_fee
      @parking_fee = ParkingFee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parking_fee_params
      params.require(:parking_fee).permit(:parking_fees_type, :parking_fees_description, :parking_fees_money)
    end
end

app/helpers/parking_fees_helper.rb
module ParkingFeesHelper
end

app/views/parking_fees/_form.html.erb
<%= form_with(model: parking_fee) do |form| %>
<% if parking_fee.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(parking_fee.errors.count, "error") %> prohibited this parking_fee from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% parking_fee.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :parking_fees_type, class: label_class %>
          <%= form.text_field :parking_fees_type, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :parking_fees_description, class: label_class %>
          <%= form.text_field :parking_fees_description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :parking_fees_money, class: label_class %>
          <%= form.number_field :parking_fees_money, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if parking_fee.persisted? %>
<%= link_to "Cancel", parking_fee, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", parking_fees_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/parking_fees/_parking_fee.html.erb
<div id="<%= dom_id parking_fee %>">
  <p>
    <strong>Parking fees type:</strong>
    <%= parking_fee.parking_fees_type %>
  </p>

  <p>
    <strong>Parking fees description:</strong>
    <%= parking_fee.parking_fees_description %>
  </p>

  <p>
    <strong>Parking fees money:</strong>
    <%= parking_fee.parking_fees_money %>
  </p>

</div>

app/views/parking_fees/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit parking_fee</h1>
    <% if @parking_fee.persisted? %>
    <%= button_to 'Destroy', @parking_fee, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', parking_fee: @parking_fee %>
</div>

app/views/parking_fees/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Parking_fees</h1>

    <%= link_to new_parking_fee_path, class: button_class(theme: "primary") do %>
    Add New Parking fee
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking fees type</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking fees description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking fees money</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @parking_fees.each do |parking_fee| %>
      <%= content_tag :tr, id: dom_id(parking_fee), class: dom_class(parking_fee) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_fee.parking_fees_type %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_fee.parking_fees_description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_fee.parking_fees_money %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', parking_fee %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/parking_fees/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New parking_fee</h1>

  <%= render 'form', parking_fee: @parking_fee %>
</div>

app/views/parking_fees/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Parking_fee</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to parking_fees_path, class: button_class(theme: "transparent") do %>
      All Parking_fees
      <% end %>
      <%= link_to edit_parking_fee_path(@parking_fee), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Parking fees type:</p>
        <p><%= @parking_fee.parking_fees_type %></p>
      </li>
      <li>
        <p class="font-semibold">Parking fees description:</p>
        <p><%= @parking_fee.parking_fees_description %></p>
      </li>
      <li>
        <p class="font-semibold">Parking fees money:</p>
        <p><%= @parking_fee.parking_fees_money %></p>
      </li>
  </ul>
</div>