config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :parking_fees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parking_statuses
  resources :permissions
  resources :supervisors
  resources :role_of_supervisors
  resources :parking_slots
  resources :cars
  resources :customers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'parking_statuses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/parking_statuses_controller.rb
class ParkingStatusesController < ApplicationController
  before_action :set_parking_status, only: %i[ show edit update destroy ]

  # GET /parking_statuses or /parking_statuses.json
  def index
    @parking_statuses = ParkingStatus.all
  end

  # GET /parking_statuses/1 or /parking_statuses/1.json
  def show
  end

  # GET /parking_statuses/new
  def new
    @parking_status = ParkingStatus.new
  end

  # GET /parking_statuses/1/edit
  def edit
  end

  # POST /parking_statuses or /parking_statuses.json
  def create
    @parking_status = ParkingStatus.new(parking_status_params)

    respond_to do |format|
      if @parking_status.save
        format.html { redirect_to parking_status_url(@parking_status), notice: "Parking status was successfully created." }
        format.json { render :show, status: :created, location: @parking_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parking_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_statuses/1 or /parking_statuses/1.json
  def update
    respond_to do |format|
      if @parking_status.update(parking_status_params)
        format.html { redirect_to parking_status_url(@parking_status), notice: "Parking status was successfully updated." }
        format.json { render :show, status: :ok, location: @parking_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_statuses/1 or /parking_statuses/1.json
  def destroy
    @parking_status.destroy

    respond_to do |format|
      format.html { redirect_to parking_statuses_url, notice: "Parking status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_status
      @parking_status = ParkingStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parking_status_params
      params.require(:parking_status).permit(:parking_fee_id, :parking_slot_id, :car_id, :customer_id, :permission_id)
    end
end

app/helpers/parking_statuses_helper.rb
module ParkingStatusesHelper
end

app/views/parking_statuses/_form.html.erb
<%= form_with(model: parking_status) do |form| %>
<% if parking_status.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(parking_status.errors.count, "error") %> prohibited this parking_status from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% parking_status.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :parking_fee_id, class: label_class %>
        <%= form.select :parking_fee_id, options_from_collection_for_select(
          ParkingFee.all, 'id', 'parking_fees_type', selected = parking_status.parking_fee_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :parking_slot_id, class: label_class %>
        <%= form.select :parking_slot_id, options_from_collection_for_select(
          ParkingSlot.all, 'id', 'parking_slot_type', selected = parking_status.parking_slot_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :car_id, class: label_class %>
        <%= form.select :car_id, options_from_collection_for_select(
          Car.all, 'id', 'car_category', selected = parking_status.car_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :customer_id, class: label_class %>
        <%= form.select :customer_id, options_from_collection_for_select(
          Customer.all, 'id', 'customer_name', selected = parking_status.customer_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :permission_id, class: label_class %>
        <%= form.select :permission_id, options_from_collection_for_select(
          Permission.all, 'id', 'permission_date', selected = parking_status.permission_id), class: label_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if parking_status.persisted? %>
<%= link_to "Cancel", parking_status, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", parking_statuses_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/parking_statuses/_parking_status.html.erb
<div id="<%= dom_id parking_status %>">
  <p>
    <strong>Parking fee:</strong>
    <%= parking_status.parking_fee_id %>
  </p>

  <p>
    <strong>Parking slot:</strong>
    <%= parking_status.parking_slot_id %>
  </p>

  <p>
    <strong>Car:</strong>
    <%= parking_status.car_id %>
  </p>

  <p>
    <strong>Customer:</strong>
    <%= parking_status.customer_id %>
  </p>

  <p>
    <strong>Permission:</strong>
    <%= parking_status.permission_id %>
  </p>

</div>

app/views/parking_statuses/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit parking_status</h1>
    <% if @parking_status.persisted? %>
    <%= button_to 'Destroy', @parking_status, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', parking_status: @parking_status %>
</div>

app/views/parking_statuses/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Parking_statuses</h1>

    <%= link_to new_parking_status_path, class: button_class(theme: "primary") do %>
    Add New Parking status
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking fee</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Parking slot</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Car</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Customer</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Permission</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @parking_statuses.each do |parking_status| %>
      <%= content_tag :tr, id: dom_id(parking_status), class: dom_class(parking_status) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_status.parking_fee.parking_fees_type %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_status.parking_slot.parking_slot_type %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_status.car.car_category %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_status.customer.customer_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= parking_status.permission.permission_date %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', parking_status %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/parking_statuses/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New parking_status</h1>

  <%= render 'form', parking_status: @parking_status %>
</div>

app/views/parking_statuses/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Parking_status</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to parking_statuses_path, class: button_class(theme: "transparent") do %>
      All Parking_statuses
      <% end %>
      <%= link_to edit_parking_status_path(@parking_status), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Parking fee:</p>
        <p><%= @parking_status.parking_fee.parking_fees_type %></p>
      </li>
      <li>
        <p class="font-semibold">Parking slot:</p>
        <p><%= @parking_status.parking_slot.parking_slot_type %></p>
      </li>
      <li>
        <p class="font-semibold">Car:</p>
        <p><%= @parking_status.car.car_category %></p>
      </li>
      <li>
        <p class="font-semibold">Customer:</p>
        <p><%= @parking_status.customer.customer_name %></p>
      </li>
      <li>
        <p class="font-semibold">Permission:</p>
        <p><%= @parking_status.permission.permission_date%></p>
      </li>
  </ul>
</div>