config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :parking_fees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :parking_statuses
  resources :permissions
  resources :supervisors
  resources :role_of_supervisors
  resources :parking_slots
  resources :cars
  resources :customers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'parking_statuses#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :customer
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:customer_id, :car_category, :car_description)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Customer:</strong>
    <%= car.customer_id %>
  </p>

  <p>
    <strong>Car category:</strong>
    <%= car.car_category %>
  </p>

  <p>
    <strong>Car description:</strong>
    <%= car.car_description %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
<% if car.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% car.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :customer_id, class: label_class %>
          <%= form.select :customer_id, options_from_collection_for_select(
            Customer.all, 'id', 'customer_name', selected = car.customer_id), class: label_class %>
      </div>
  <div class="mb-6">
        <%= form.label :car_category, class: label_class %>
          <%= form.text_field :car_category, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :car_description, class: label_class %>
          <%= form.text_field :car_description, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if car.persisted? %>
<%= link_to "Cancel", car, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", cars_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/cars/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit car</h1>
    <% if @car.persisted? %>
    <%= button_to 'Destroy', @car, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', car: @car %>
</div>

app/views/cars/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Cars</h1>

    <%= link_to new_car_path, class: button_class(theme: "primary") do %>
    Add New Car
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Customer</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Car category</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Car description</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @cars.each do |car| %>
      <%= content_tag :tr, id: dom_id(car), class: dom_class(car) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= car.customer.customer_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= car.car_category %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= car.car_description %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', car %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/cars/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New car</h1>

  <%= render 'form', car: @car %>
</div>

app/views/cars/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Car</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to cars_path, class: button_class(theme: "transparent") do %>
      All Cars
      <% end %>
      <%= link_to edit_car_path(@car), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Customer:</p>
        <p><%= @car.customer.customer_name %></p>
      </li>
      <li>
        <p class="font-semibold">Car category:</p>
        <p><%= @car.car_category %></p>
      </li>
      <li>
        <p class="font-semibold">Car description:</p>
        <p><%= @car.car_description %></p>
      </li>
  </ul>
</div>